=== raysparrow/MarkManagment/PRXFinalProject/WebContent/data/DBValidate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" type="studentDetail" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Teacher" type="teacherDetail" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="studentDetail">
        <xs:sequence>
            <xs:element name="StudentName" type="xs:string"/>
            <xs:element name="StudentID" type="studentIDCheck"/>
            <xs:element name="Classes" type="classDetail" />
            <xs:element name="Subjects" type="subjectDetail"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="studentIDCheck">
        <xs:restriction base="xs:string">
            <xs:pattern value="SE[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="subjectDetail">
        <xs:sequence>
            <xs:element name="Subject" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Teacher" type="xs:string"/>
                        <xs:element name="SubjectID" type="xs:string"/>
                        <xs:element name="SubjectName" type="xs:string"/>
                        <xs:element name="PT1" type="xs:string"/>
                        <xs:element name="PT2" type="xs:string"/>  
                        <xs:element name="ASS" type="xs:string"/>  
                        <xs:element name="FinalExam" type="xs:string"/>  
                        <xs:element name="TotalMark" type="xs:string"/>  
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="classDetail">
        <xs:sequence>
            <xs:element name="ClassName" type="xs:string" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="teacherDetail">
        <xs:sequence>
            <xs:element name="TeacherID" type="xs:string" />
            <xs:element name="TeacherName" type="xs:string" />
            <xs:element name="Mail" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== raysparrow/MarkManagment/PRXFinalProject/WebContent/Database.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="DBValidate.xsd">
    <Student>
        <StudentName>Nguyen Van A</StudentName>
        <StudentID>SE11111</StudentID>
        <Classes>
            <ClassName>IS1104</ClassName>
            <ClassName>IS1105</ClassName>
        </Classes>
        <Subjects>
            <Subject>
                <Teacher>sonnt5</Teacher>
                <SubjectID>DBW301</SubjectID>
                <SubjectName>Data warehouse</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
            <Subject>
                <Teacher>AnhBN</Teacher>
                <SubjectID>PRX301</SubjectID>
                <SubjectName>Web Development (XML)</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
            <Subject>
                <Teacher>anhpn</Teacher>
                <SubjectID>MLN101</SubjectID>
                <SubjectName>Principles of Marxism - Leninism</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
        </Subjects>
    </Student>
    <Student>
        <StudentName>Nguyen Van B</StudentName>
        <StudentID>SE22222</StudentID>
        <Classes>
            <ClassName>IS1104</ClassName>
        </Classes>
        <Subjects>
            <Subject>
                <Teacher>AnhBN</Teacher>
                <SubjectID>PRX301</SubjectID>
                <SubjectName>Web Development (XML)</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
            <Subject>
                <Teacher>anhpn</Teacher>
                <SubjectID>MLN101</SubjectID>
                <SubjectName>Principles of Marxism - Leninism</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
        </Subjects>
    </Student>
    <Teacher>
        <TeacherID>sonnt5</TeacherID>
        <TeacherName>Ngô Tùng Sơn</TeacherName>
        <Mail>sonnt69@fe.edu.vn</Mail>
    </Teacher>
    <Teacher>
        <TeacherID>AnhBN</TeacherID>
        <TeacherName>Bùi Ngọc Anh</TeacherName>
        <Mail>AnhBN5@fe.edu.vn</Mail>
    </Teacher>
    <Teacher>
        <TeacherID>anhpn</TeacherID>
        <TeacherName>Phạm Ngọc Anh</TeacherName>
        <Mail>AnhPN16@fe.edu.vn</Mail>
    </Teacher>
</Students>

=== raysparrow/MarkManagment/PRXFinalProject/WebContent/data/Database.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="DBValidate.xsd">
    <Student>
        <StudentName>Nguyen Van A</StudentName>
        <StudentID>SE11111</StudentID>
        <StudentMail>AnvSE11111@fpt.edu.vn</StudentMail>
        <StudentPhone>0123 456 789</StudentPhone>
        <StudentDOB>12/12/2018</StudentDOB>
        <StudentSex>Male</StudentSex>
        <StudentCourse>K11</StudentCourse>
        <StudentGPA>3.4</StudentGPA>
        <Classes>
            <ClassName>IS1104</ClassName>
            <ClassName>IS1105</ClassName>
        </Classes>
        <Subjects>
            <Subject>
                <ClassName>IS1105</ClassName>
                <TeacherID>sonnt5</TeacherID>
                <SubjectID>DBW301</SubjectID>
                <SubjectName>Data warehouse</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
            <Subject>
                <ClassName>IS1104</ClassName>
                <TeacherID>AnhBN</TeacherID>
                <SubjectID>PRX301</SubjectID>
                <SubjectName>Web Development (XML)</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
            <Subject>
                <ClassName>IS1104</ClassName>
                <TeacherID>anhpn</TeacherID>
                <SubjectID>MLN101</SubjectID>
                <SubjectName>Principles of Marxism - Leninism</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
        </Subjects>
    </Student>
    <Student>
        <StudentName>Nguyen Van B</StudentName>
        <StudentID>SE22222</StudentID>
        <StudentMail>AnvSE11111@fpt.edu.vn</StudentMail>
        <StudentPhone>0123 456 789</StudentPhone>
        <StudentDOB>12/12/2018</StudentDOB>
        <StudentSex>Male</StudentSex>
        <StudentCourse>K11</StudentCourse>
        <StudentGPA>3.4</StudentGPA>
        <Classes>
            <ClassName>IS1104</ClassName>
        </Classes>
        <Subjects>
            <Subject>
                <ClassName>IS1104</ClassName>
                <TeacherID>AnhBN</TeacherID>
                <SubjectID>PRX301</SubjectID>
                <SubjectName>Web Development (XML)</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
            <Subject>
                <ClassName>IS1104</ClassName>
                <TeacherID>anhpn</TeacherID>
                <SubjectID>MLN101</SubjectID>
                <SubjectName>Principles of Marxism - Leninism</SubjectName>
                <PT1>5</PT1>
                <PT2>5</PT2>
                <ASS>5</ASS>
                <FinalExam>5</FinalExam>
                <TotalMark>5</TotalMark>    
            </Subject>
        </Subjects>
    </Student>
    <Teacher>
        <TeacherID>sonnt5</TeacherID>
        <TeacherName>Ngô Tùng Sơn</TeacherName>
        <Phone>0999999999</Phone>
        <Mail>sonnt69@fe.edu.vn</Mail>
    </Teacher>
    <Teacher>
        <TeacherID>AnhBN</TeacherID>
        <TeacherName>Bùi Ngọc Anh</TeacherName>
        <Phone>0999999999</Phone>
        <Mail>AnhBN5@fe.edu.vn</Mail>
    </Teacher>
    <Teacher>
        <TeacherID>anhpn</TeacherID>
        <TeacherName>Phạm Ngọc Anh</TeacherName>
        <Phone>0999999999</Phone>
        <Mail>AnhPN16@fe.edu.vn</Mail>
    </Teacher>
</Students>
